#!/usr/bin/env bash

npx @getmeli/cli upload \
    ./storybook-static \
    --token $MELI_CLIENT_STORYBOOK_TOKEN \
    --site $MELI_CLIENT_STORYBOOK_SITE_ID \
    --url https://$MELI_SERVER \
    --branch $CI_COMMIT_BRANCH$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME \
    --release $CI_COMMIT_SHA
