name: Deploy

on:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Build Docker Image
        run: docker build -t dokku/naviate-api:latest .
      - name: Upload Docker Image
        run: |
          docker save dokku/naviate-api:latest | \
            bzip2 | \
            ssh root@${{ secrets.API_SERVER }} "bunzip2 | docker load"
      - name: Deploy Docker Image
        run: |
          ssh root@${{ secrets.API_SERVER }} \
            "dokku tags:create naviate-api previous; dokku tags:deploy naviate-api latest"
