name: Docker

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build for musl
        run: ./scripts/build_alpine
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/Eigently/naviate-server/alpine:${{ github.sha }}
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull Docker Image by SHA
        run: docker pull ghcr.io/Eigently/naviate-server/alpine:${{ github.sha }}
      - name: Rename Docker Image
        run: |
          docker image tag \
            ghcr.io/Eigently/naviate-server/alpine:${{ github.sha }} \
            dokku/naviate-api:latest
      - name: Upload Docker Image
        run: |
          docker save dokku/naviate-api:latest | \
            bzip2 | \
            ssh root@${{ secrets.API_SERVER }} "bunzip2 | docker load"
      - name: Deploy Docker Image
        run: |
          ssh root@${{ secrets.API_SERVER }} \
            "dokku tags:create naviate-api previous; dokku tags:deploy naviate-api latest"
