import { ComponentProps } from "react";
import { Story } from "@storybook/react";

import { DAtis } from "./d_atis";

export default {
  title: "Aviation/D-ATIS",
  component: DAtis,
  argTypes: {
    handleGetDAtis: { action: "handleGetDAtis" },
  },
};

const Template: Story<ComponentProps<typeof DAtis>> = (args) => (
  <DAtis {...args} />
);

export const Primary = Template.bind({});
Primary.args = {
  dAtisData: {
    status: "succeeded",
    data: {
      icaoCode: "KATL",
      dAtisType: "SEPARATED",
      dAtisDeparture:
        "ATL ARR INFO F 0052Z. 27006KT 10SM FEW100 FEW250 27/13 A3012 (THREE ZERO ONE TWO). SIMULTANEOUS APCHS IN USE VIS 26R, ILS 27L, VIS 28. NOTAMS... TWY SJ CLSD. RWY 26R TDZL OTS. ILS RWY 27R OTS. CRANE 260 FEET AGL ABOVE MAIN TERMINAL. CRANE 135 FEET AGL WEST END OF TAXIWAY ECHO. BIRD ACTIVITY VC OF ARPT. UAS ACTIVITY 5 MILES NW OF ATLANTA AIRPORT BELOW 200 FEET. OPERATE TRANSPONDER WITH MODE C ON ALL RAMPS, TWYS AND RWYS.. ...ADVS YOU HAVE INFO F.",
      dAtisArrival:
        "ATL DEP INFO R 0052Z. 27006KT 10SM FEW100 FEW250 27/13 A3012 (THREE ZERO ONE TWO). SIMUL DEPS, DEPG RWYS, 26L, 27R. XPECT RNAV OFF THE GROUND DEPTG RWY 26L, XPECT RNAV OFF THE GROUND DEPTG RWY 27R. GROUND CONTROL WILL ASSIGN RUNWAY WITH TAXI INSTRUCTIONS. NOTAMS... TWY SJ CLSD. CRANE 260 FEET AGL ABOVE MAIN TERMINAL. CRANE 135 FEET AGL WEST END OF TAXIWAY ECHO. BIRD ACTIVITY VC OF ARPT. UAS ACTIVITY 5 MILES NW OF ATLANTA AIRPORT BELOW 200 FEET. OPERATE TRANSPONDER WITH MODE C ON ALL RAMPS, TWYS AND RWYS.. ...ADVS YOU HAVE INFO R.",
    },
  },
};

export const Idle = Template.bind({});
Idle.args = {
  dAtisData: {
    status: "idle",
    data: {
      icaoCode: "KATL",
      dAtisType: "SEPARATED",
      dAtisDeparture:
        "ATL ARR INFO F 0052Z. 27006KT 10SM FEW100 FEW250 27/13 A3012 (THREE ZERO ONE TWO). SIMULTANEOUS APCHS IN USE VIS 26R, ILS 27L, VIS 28. NOTAMS... TWY SJ CLSD. RWY 26R TDZL OTS. ILS RWY 27R OTS. CRANE 260 FEET AGL ABOVE MAIN TERMINAL. CRANE 135 FEET AGL WEST END OF TAXIWAY ECHO. BIRD ACTIVITY VC OF ARPT. UAS ACTIVITY 5 MILES NW OF ATLANTA AIRPORT BELOW 200 FEET. OPERATE TRANSPONDER WITH MODE C ON ALL RAMPS, TWYS AND RWYS.. ...ADVS YOU HAVE INFO F.",
      dAtisArrival:
        "ATL DEP INFO R 0052Z. 27006KT 10SM FEW100 FEW250 27/13 A3012 (THREE ZERO ONE TWO). SIMUL DEPS, DEPG RWYS, 26L, 27R. XPECT RNAV OFF THE GROUND DEPTG RWY 26L, XPECT RNAV OFF THE GROUND DEPTG RWY 27R. GROUND CONTROL WILL ASSIGN RUNWAY WITH TAXI INSTRUCTIONS. NOTAMS... TWY SJ CLSD. CRANE 260 FEET AGL ABOVE MAIN TERMINAL. CRANE 135 FEET AGL WEST END OF TAXIWAY ECHO. BIRD ACTIVITY VC OF ARPT. UAS ACTIVITY 5 MILES NW OF ATLANTA AIRPORT BELOW 200 FEET. OPERATE TRANSPONDER WITH MODE C ON ALL RAMPS, TWYS AND RWYS.. ...ADVS YOU HAVE INFO R.",
    },
  },
};

export const Separated = Template.bind({});
Separated.args = {
  dAtisData: {
    status: "succeeded",
    data: {
      icaoCode: "KATL",
      dAtisType: "SEPARATED",
      dAtisDeparture:
        "ATL ARR INFO F 0052Z. 27006KT 10SM FEW100 FEW250 27/13 A3012 (THREE ZERO ONE TWO). SIMULTANEOUS APCHS IN USE VIS 26R, ILS 27L, VIS 28. NOTAMS... TWY SJ CLSD. RWY 26R TDZL OTS. ILS RWY 27R OTS. CRANE 260 FEET AGL ABOVE MAIN TERMINAL. CRANE 135 FEET AGL WEST END OF TAXIWAY ECHO. BIRD ACTIVITY VC OF ARPT. UAS ACTIVITY 5 MILES NW OF ATLANTA AIRPORT BELOW 200 FEET. OPERATE TRANSPONDER WITH MODE C ON ALL RAMPS, TWYS AND RWYS.. ...ADVS YOU HAVE INFO F.",
      dAtisArrival:
        "ATL DEP INFO R 0052Z. 27006KT 10SM FEW100 FEW250 27/13 A3012 (THREE ZERO ONE TWO). SIMUL DEPS, DEPG RWYS, 26L, 27R. XPECT RNAV OFF THE GROUND DEPTG RWY 26L, XPECT RNAV OFF THE GROUND DEPTG RWY 27R. GROUND CONTROL WILL ASSIGN RUNWAY WITH TAXI INSTRUCTIONS. NOTAMS... TWY SJ CLSD. CRANE 260 FEET AGL ABOVE MAIN TERMINAL. CRANE 135 FEET AGL WEST END OF TAXIWAY ECHO. BIRD ACTIVITY VC OF ARPT. UAS ACTIVITY 5 MILES NW OF ATLANTA AIRPORT BELOW 200 FEET. OPERATE TRANSPONDER WITH MODE C ON ALL RAMPS, TWYS AND RWYS.. ...ADVS YOU HAVE INFO R.",
    },
  },
};

export const Combined = Template.bind({});
Combined.args = {
  dAtisData: {
    status: "succeeded",
    data: {
      icaoCode: "KJFK",
      dAtisType: "COMBINED",
      dAtisCombined:
        "JFK ATIS INFO U 0051Z. 21012KT 10SM FEW050 SCT095 BKN110 BKN160 BKN250 19/17 A2991 (TWO NINER NINER ONE) RMK LTG DSNT SE RAE45 TSE24. APPROACH IN USE ILS RY 22L, ILS RY 22R. DEPG RY 22R. NOTAMS... RWY 13R, 31L CLSD, RWY 13L, 31R CLSD. JFK VOR OTS. HAZD WX INFO FOR NY METRO AREA AVBL ON FSS. SWAP IN EFFECT EXPECT REROUTES. BIRD ACTIVITY VICINITY ARPT. NUM CRANES OPERATING AT JFK. READBACK ALL RWY HOLD SHORT INSTRUCTIONS. ...ADVS YOU HAVE INFO U.",
    },
  },
};

export const Loading = Template.bind({});
Loading.args = {
  dAtisData: {
    status: "loading",
  },
};

export const Failed = Template.bind({});
Failed.args = {
  dAtisData: {
    status: "failed",
    error: "Invalid or Unsupported ICAO Code.",
  },
};
