stages:
  - test
  - build
  - share
  - deploy

include:
  - server/gitlab/workflows/docker.yml
  - server/gitlab/workflows/build.yml
  - server/gitlab/workflows/test.yml
  - server/gitlab/workflows/deploy.yml
