#!/usr/bin/env sh
docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
docker build -t $CI_REGISTRY_IMAGE/server/alpine:$CI_COMMIT_SHORT_SHA --build-arg COMMIT_SHA=$CI_COMMIT_SHA .
docker push $CI_REGISTRY_IMAGE/server/alpine:$CI_COMMIT_SHORT_SHA
docker image tag $CI_REGISTRY_IMAGE/server/alpine:$CI_COMMIT_SHORT_SHA dokku/naviate-api:latest
docker save dokku/naviate-api:latest -o naviate.dockerimage
